
REST_IP=
REST_PORT=8081
EVENT_SERVER_IP=
EVENT_SERVER_PORT=8082
DB_HOST=""
DB_NAME=""
LOG_PATH=../log/yolo-detector-service.log

RECORDINGS_TMP_DIR=/home/khomin/Documents/PROJECTS/YOLO_detector/record_temp/

SESSION_ALLOWED_CLASSES=person,dog,bird,cat

SESSION_TASK_TIMER=1s
TARGET_THRESHOLD_DURATION=3s

# Video encoding codec to use
# Options: H264 (recommended for compatibility), H265 (better efficiency)
VIDEO_CODEC=H264

APP_ENV="development"